Feature/10 create a swagger document
genesis-tech-tribe/nishiki-documents pull request #14
Opened 2023-10-19 05:37 UTC by hitohata

## Overviews of implementation

Add an OpenAPI document

## Review points

* add a document

2023-10-21 09:10 UTC, taniguchiiqqq requested changes
Thank you for creating the OpenAPI Specification definition file. I mentioned some points basically to make this doc work on the Swagger UI.

2023-10-21 09:10 UTC, taniguchiiqqq commented on web-api/nishiki-web-api.yaml
> +  /users/:userId/containers:
The "parameters" key is needed for this doc to work on the Swagger UI.

```
      parameters:
        - name: userId
          in: path
          description: ID of user
          required: true
          schema:
            type: string
```

2023-10-21 09:10 UTC, taniguchiiqqq commented on web-api/nishiki-web-api.yaml
> +      responses:
The "parameters" key is needed for this doc to work on the Swagger UI.

```
      parameters:
        - name: containerId
          in: path
          description: ID of container
          required: true
          schema:
            type: string
```

2023-10-21 09:10 UTC, taniguchiiqqq commented on web-api/nishiki-web-api.yaml
> +      requestBody:
The "parameters" key is needed for this doc to work on the Swagger UI.

```
      parameters:
        - name: containerId
          in: path
          description: ID of container
          required: true
          schema:
            type: string
```

2023-10-21 09:10 UTC, taniguchiiqqq commented on web-api/nishiki-web-api.yaml
> +      requestBody:
I think this endpoint requires a request body, so having a "required" key is better.

2023-10-21 09:10 UTC, taniguchiiqqq commented on web-api/nishiki-web-api.yaml
> +      requestBody:
The "parameters" key is needed for this doc to work on the Swagger UI.

```
      parameters:
        - name: containerId
          in: path
          description: ID of container
          required: true
          schema:
            type: string
        - name: foodId
          in: path
          description: ID of food
          required: true
          schema:
            type: string
```

2023-10-21 09:10 UTC, taniguchiiqqq commented on web-api/nishiki-web-api.yaml
> +        - container
The "parameters" key is needed for this doc to work on the Swagger UI.

```
      parameters:
        - name: containerId
          in: path
          description: ID of container
          required: true
          schema:
            type: string
        - name: foodId
          in: path
          description: ID of food
          required: true
          schema:
            type: string
```

2023-10-21 09:10 UTC, taniguchiiqqq commented on web-api/nishiki-web-api.yaml
> +        - group
The "parameters" key is needed for this doc to work on the Swagger UI.

```
      parameters:
        - name: grouoId
          in: path
          description: ID of group
          required: true
          schema:
            type: string
```

2023-10-21 09:10 UTC, taniguchiiqqq commented on web-api/nishiki-web-api.yaml
> +        - group
The "parameters" key is needed for this doc to work on the Swagger UI.

```
      parameters:
        - name: grouoId
          in: path
          description: ID of group
          required: true
          schema:
            type: string
        - name: userId
          in: path
          description: ID of user
          required: true
          schema:
            type: string
```

2023-10-21 09:10 UTC, taniguchiiqqq commented on web-api/nishiki-web-api.yaml
> +        - group
The "parameters" key is needed for this doc to work on the Swagger UI.

```
      parameters:
        - name: grouoId
          in: path
          description: ID of group
          required: true
          schema:
            type: string
        - name: userId
          in: path
          description: ID of user
          required: true
          schema:
            type: string
```

2023-10-21 18:46 UTC, hitohata commented
@taniguchiiqqq 
Thank you for the review! I fixed it.

2023-10-22 01:09 UTC, taniguchiiqqq commented
@hitohata 
Thank you for fixing.
Could you remove colons : from path parameters? {Path parameter's name} must have the same name as the parameters: section's -name.

2023-10-22 01:31 UTC, hitohata commented
@taniguchiiqqq 
Sorry, I deleted the colon symbol.

2023-10-22 03:01 UTC, taniguchiiqqq approved these changes
Thank you!!

2023-10-22 03:03 UTC, merged