doc: add group document
genesis-tech-tribe/nishiki-documents pull request #48
Opened 2023-11-13 10:02 UTC by taniguchiiqqq

## Overview
add group document

## review points
Is the relationship between Group and Container Composition? Or Should I change it to Aggregation cuz Groups can exist without Containers?

2023-11-13 16:23 UTC, hitohata requested changes
>Is the relationship between Group and Container Composition? Or Should I change it to Aggregation cuz Groups can exist without Containers?

I cannot get this meaning. Do you mean you need to divide Group and Container into different pages? If so, I think do so.

To reflect the group page, you have to update the sidebars.js.
```javascript
{
          type: "category",
          label: "Group Context",
          items: [
            {
              type: "category",
              label: "Group Aggregate",
              items: [
                {
                  type: "doc",
                  label: "Group",
                  id: "domain-model/group-context/group"
                }
              ]
            },
            {
              type: "category",
              label: "Container Aggregate",
              items: [
                {
                  type: "doc",
                  label: "Container",
                  id: "domain-model/group-context/container"
                },
                {
                  type: "doc",
                  label: "Food",
                  id: "domain-model/group-context/food"
                }
              ]
            }
          ]
        }
```
https://github.com/genesis-tech-tribe/nishiki-documents/tree/main/project-document#how-to-write-document

2023-11-13 16:23 UTC, hitohata commented on project-document/docs/domain-model/group-context/group.md
> +## container IDs
This should be a capital letter.

2023-11-13 16:23 UTC, hitohata commented on project-document/docs/domain-model/group-context/group.md
> +the group is composed of users. The group class has user Id list. The Group **cannot exist** without any user.
This should be a capital letter. And "Id" should be ID because this is just a document not a code.

2023-11-13 16:23 UTC, hitohata commented on project-document/docs/domain-model/group-context/group.md
> +the group is composed of containers. The group class has container ID list. The Group **can exist** without any container.
This should be a capital letter.

2023-11-19 20:50 UTC, hitohata commented
@taniguchiiqqq 
You have changed the directory, so you have to change the ID name of each document in the sidebar.

```js
id: "domain-model/group-context/group-aggregate/group"
```

2023-11-19 21:18 UTC, taniguchiiqqq commented
@hitohata 
I really appreciate your careful review! Sorry, I totally forgot to modify sidebar.js.
What I meant in the previous comment is that  I'm not sure if the following expression `The group is composed of containers.` in `group.md` is appropriate or not. Should it be `The group is an aggregate of containers.`?
I'm still deciding which is better. If containers in a group are deleted when the group is deleted, it should be composition but if not, it should be aggregation, I think.

```
## Container IDs

The group is composed of containers. The group class has container ID list. The Group **can exist** without any container.
```

2023-11-19 21:50 UTC, hitohata commented
I think aggregate and composition is not appropriate word.  Those words don't sound general. 
In group sections, it should be written about what is a group. I mean group is just a group that holds users and containers. It's a very complex complex though...

2023-11-19 21:50 UTC, hitohata approved these changes

2023-12-18 08:24 UTC, merged